### ISSUE TITLE
Ability to download from the CodeMii repository

### ISSUE THREAD

**Issue by DraconicNEO** [dhtdht020/osc-dl#30]
I feel like there should be the ability to download from the old Codemii repository, since you're still able to do it in the homebrew browser I feel like you should also be able to here.

**Comment by dhtdht020** [comment]
It seems that unfortunately, the CodeMii repository is slightly broken and therefore incompatible with our API.

**Comment by DraconicNEO** [comment]
> 
> 
> It seems that unfortunately, the CodeMii repository is slightly broken and therefore incompatible with our API.

What about Mirroring the apps in CodeMii as an archive of the Repository?

**Comment by dhtdht020** [comment]
> > It seems that unfortunately, the CodeMii repository is slightly broken and therefore incompatible with our API.
> 
> What about Mirroring the apps in CodeMii as an archive of the Repository?

I don't plan on doing that for now, though it is something to consider once we are less busy.

**Comment by larsenv** [comment]
Hidden feature: in OSC, you can change the repo that is being used, so you can choose from our HBC theme repository or the CodeMii repository.

@dhtdht020 the "backup" CodeMii server is the one that works fine.

I don't think that CodeMii will be going anywhere since teknecal bothered to update the site with the HBB source code... I have no idea how to contact that guy.
